eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


    
management:
  endpoint:
    beans:
      enabled: true
      
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  
  endpoints:
    web:
      exposure:
        include:
        - '*'
      base-path: /product-management